#!/usr/bin/env bash

docker buildx build --push --platform linux/arm64,linux/amd64,linux/arm/v6,linux/arm/v7,linux/386 --build-arg TERRAFORM_VER=1.0.4 --build-arg ALPINE_VER=3.15 --tag kinghrothgar/terraform:1.0.4 .
